### ISSUE TITLE
[Feature]: Add Authentication and User Registration

### ISSUE THREAD

**Issue by hariketsheth** [srummanf/Blog---MEN-Stack#1]
## Background
- The current state of the Project lacks user authentication and registration, which is essential
- Routes need to be secured 

## Proposal
- This issue aims to implement User Authentication and Registration using `Passport.js` and `bcrypt`
- This will ensure that users can securely create accounts, log in, and access their account

## Tasks
- [X] Implement Passport.js and LocalStrategy for Authentication
- [X] Integrate bcrypt for secure Password Hashing
- [X] Connected User Model to store user information
- [X] Setup Registration, Login, Logout Routes with error handling

@srummanf Kindly assign this issue to me ! 😊💫

**Comment by srummanf** [comment]
That is a nice idea! Sure Bhaiyya, you can work on it.
